GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons/6482ff41a3ad2e2eedbc736b

###
GET http://localhost:3001/api/persons/124

###
DELETE http://localhost:3001/api/persons/6612
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Aku Ankka",
    "number": "313"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jaska Jokunen",
    "number": "313"
}